services:
  postgres:
    image: postgres:14.10-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: car-management
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
    networks:
      - car-management-network
    volumes:
      - ./db/init-db:/docker-entrypoint-initdb.d
    container_name: car-management-db
    healthcheck:
      test: [ "CMD-SHELL", "psql -U postgres -d car-management -t 15 -c 'SELECT 1'" ]
      interval: "5s"
      timeout: "15s"
      retries: 10
  liquibase:
    image: liquibase/liquibase:latest-alpine
    container_name: car-management-liquibase
    depends_on:
      postgres:
        condition: "service_healthy"
    volumes:
      - ./db/changelog:/liquibase/changelog
    command: --logLevel=info --defaultsFile=/liquibase/changelog/liquibase-docker.properties --contexts=dev update
    networks:
      - car-management-network
  backend:
    #image: np-challenge/car-management-api
    container_name: car-management-api
    depends_on:
      postgres:
        condition: "service_healthy"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - car-management-network
    environment:
      - db_host=car-management-db
      - db_port=5432
      - db_name=car-management
      - db_schema=car_management
      - db_user=postgres
      - db_password=postgres
      - db_pool_min_size=2
      - db_pool_max_size=5
      - QUARKUS_PROFILE=prod
    ports:
      - "8080:8080"
networks:
  car-management-network:
    driver: bridge
