### Authorization by token, part 2. Use token to authorize.
GET http://localhost:8080/car

###
GET http://localhost:8080/car/67d4b756-aeb6-4918-8f86-c40179b285c8

###
POST http://localhost:8080/car
Content-Type: application/json

{ "brand": "BMW", "engineType": "BEV", "model": "7-series" }

####
DELETE http://localhost:8080/car/67d4b756-aeb6-4918-8f86-c40179b285c8


