
-- TO IMPLEMENT

set search_path to car_management;

ALTER TABLE T_CAR

ADD COLUMN SEATS SMALLINT,
ADD COLUMN LICENSE_PLATE VARCHAR(16),
ADD COLUMN AUTONOMY SMALLINT,
ADD COLUMN COLOR VARCHAR(16),
ADD COLUMN IMAGE BLOB, /* BYTEA maybe? */
ADD COLUMN IS_AVAILABLE BOOLEAN; 
-- 0 - Reserved / 1 - Available
